spring:
  datasource:
    url: jdbc:mysql://localhost:3306/calories_calculator_prod?serverTimezone=UTC
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false