spring:
  datasource:
    url: jdbc:mysql://localhost:3306/calories_calculator_dev?serverTimezone=UTC
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax.persistence.schema-generation:
#        create-source: metadata
#        scripts:
#          action: create
#          create-target: calories_calculator_db_create.sql